# 监听地址和端口
bind-addr 127.0.0.1
bind-port 58

# 国内上游、可信上游、均为支持ECS的DNS over TLS
china-dns tls://223.6.6.6,tls://223.5.5.5
trust-dns tls://208.67.222.222,tls://94.140.14.14,tls://94.140.15.15,tls://9.9.9.11,tls://149.112.112.11

# 域名列表，用于分流
chnlist-file /etc/chinadns/chnlist.txt
gfwlist-file /etc/chinadns/gfwlist.txt
chnlist-first

# 收集 tag:chn、tag:gfw 域名的 IP
add-tagchn-ip chnip,chnip6
add-taggfw-ip gfwip,gfwip6

# 用于测试 tag:none 域名的 IP (国内上游)
ipset-name4 chnroute
ipset-name6 chnroute6

# dns 缓存
cache 40960
cache-stale 86400
cache-refresh 20

# verdict 缓存 (用于 tag:none 域名)
verdict-cache 4096

# 详细日志
# verbose
